// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"snake-tournament/internal/iface"
	"snake-tournament/models"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/bson"
)

// NewMockIGameRepository creates a new instance of MockIGameRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIGameRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIGameRepository {
	mock := &MockIGameRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIGameRepository is an autogenerated mock type for the IGameRepository type
type MockIGameRepository struct {
	mock.Mock
}

type MockIGameRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIGameRepository) EXPECT() *MockIGameRepository_Expecter {
	return &MockIGameRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIGameRepository
func (_mock *MockIGameRepository) Create(ctx context.Context, model iface.IModel) error {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, iface.IModel) error); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIGameRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIGameRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model iface.IModel
func (_e *MockIGameRepository_Expecter) Create(ctx interface{}, model interface{}) *MockIGameRepository_Create_Call {
	return &MockIGameRepository_Create_Call{Call: _e.mock.On("Create", ctx, model)}
}

func (_c *MockIGameRepository_Create_Call) Run(run func(ctx context.Context, model iface.IModel)) *MockIGameRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 iface.IModel
		if args[1] != nil {
			arg1 = args[1].(iface.IModel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIGameRepository_Create_Call) Return(err error) *MockIGameRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIGameRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model iface.IModel) error) *MockIGameRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIGameRepository
func (_mock *MockIGameRepository) Delete(ctx context.Context, objectID bson.ObjectID) error {
	ret := _mock.Called(ctx, objectID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID) error); ok {
		r0 = returnFunc(ctx, objectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIGameRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIGameRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - objectID bson.ObjectID
func (_e *MockIGameRepository_Expecter) Delete(ctx interface{}, objectID interface{}) *MockIGameRepository_Delete_Call {
	return &MockIGameRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, objectID)}
}

func (_c *MockIGameRepository_Delete_Call) Run(run func(ctx context.Context, objectID bson.ObjectID)) *MockIGameRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIGameRepository_Delete_Call) Return(err error) *MockIGameRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIGameRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, objectID bson.ObjectID) error) *MockIGameRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAvailableToEnterGame provides a mock function for the type MockIGameRepository
func (_mock *MockIGameRepository) FindAvailableToEnterGame(ctx context.Context, playerCount int, userId string) *models.Game {
	ret := _mock.Called(ctx, playerCount, userId)

	if len(ret) == 0 {
		panic("no return value specified for FindAvailableToEnterGame")
	}

	var r0 *models.Game
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) *models.Game); ok {
		r0 = returnFunc(ctx, playerCount, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Game)
		}
	}
	return r0
}

// MockIGameRepository_FindAvailableToEnterGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAvailableToEnterGame'
type MockIGameRepository_FindAvailableToEnterGame_Call struct {
	*mock.Call
}

// FindAvailableToEnterGame is a helper method to define mock.On call
//   - ctx context.Context
//   - playerCount int
//   - userId string
func (_e *MockIGameRepository_Expecter) FindAvailableToEnterGame(ctx interface{}, playerCount interface{}, userId interface{}) *MockIGameRepository_FindAvailableToEnterGame_Call {
	return &MockIGameRepository_FindAvailableToEnterGame_Call{Call: _e.mock.On("FindAvailableToEnterGame", ctx, playerCount, userId)}
}

func (_c *MockIGameRepository_FindAvailableToEnterGame_Call) Run(run func(ctx context.Context, playerCount int, userId string)) *MockIGameRepository_FindAvailableToEnterGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIGameRepository_FindAvailableToEnterGame_Call) Return(game *models.Game) *MockIGameRepository_FindAvailableToEnterGame_Call {
	_c.Call.Return(game)
	return _c
}

func (_c *MockIGameRepository_FindAvailableToEnterGame_Call) RunAndReturn(run func(ctx context.Context, playerCount int, userId string) *models.Game) *MockIGameRepository_FindAvailableToEnterGame_Call {
	_c.Call.Return(run)
	return _c
}

// FindAvailableToEnterGames provides a mock function for the type MockIGameRepository
func (_mock *MockIGameRepository) FindAvailableToEnterGames(ctx context.Context, userId string) []models.Game {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for FindAvailableToEnterGames")
	}

	var r0 []models.Game
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.Game); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Game)
		}
	}
	return r0
}

// MockIGameRepository_FindAvailableToEnterGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAvailableToEnterGames'
type MockIGameRepository_FindAvailableToEnterGames_Call struct {
	*mock.Call
}

// FindAvailableToEnterGames is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *MockIGameRepository_Expecter) FindAvailableToEnterGames(ctx interface{}, userId interface{}) *MockIGameRepository_FindAvailableToEnterGames_Call {
	return &MockIGameRepository_FindAvailableToEnterGames_Call{Call: _e.mock.On("FindAvailableToEnterGames", ctx, userId)}
}

func (_c *MockIGameRepository_FindAvailableToEnterGames_Call) Run(run func(ctx context.Context, userId string)) *MockIGameRepository_FindAvailableToEnterGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIGameRepository_FindAvailableToEnterGames_Call) Return(games []models.Game) *MockIGameRepository_FindAvailableToEnterGames_Call {
	_c.Call.Return(games)
	return _c
}

func (_c *MockIGameRepository_FindAvailableToEnterGames_Call) RunAndReturn(run func(ctx context.Context, userId string) []models.Game) *MockIGameRepository_FindAvailableToEnterGames_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockIGameRepository
func (_mock *MockIGameRepository) FindById(ctx context.Context, id string, res *models.Game) error {
	ret := _mock.Called(ctx, id, res)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *models.Game) error); ok {
		r0 = returnFunc(ctx, id, res)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIGameRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockIGameRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - res *models.Game
func (_e *MockIGameRepository_Expecter) FindById(ctx interface{}, id interface{}, res interface{}) *MockIGameRepository_FindById_Call {
	return &MockIGameRepository_FindById_Call{Call: _e.mock.On("FindById", ctx, id, res)}
}

func (_c *MockIGameRepository_FindById_Call) Run(run func(ctx context.Context, id string, res *models.Game)) *MockIGameRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *models.Game
		if args[2] != nil {
			arg2 = args[2].(*models.Game)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIGameRepository_FindById_Call) Return(err error) *MockIGameRepository_FindById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIGameRepository_FindById_Call) RunAndReturn(run func(ctx context.Context, id string, res *models.Game) error) *MockIGameRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// FindGameByIncludeUser provides a mock function for the type MockIGameRepository
func (_mock *MockIGameRepository) FindGameByIncludeUser(ctx context.Context, userId string) ([]models.Game, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for FindGameByIncludeUser")
	}

	var r0 []models.Game
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.Game, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.Game); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Game)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGameRepository_FindGameByIncludeUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindGameByIncludeUser'
type MockIGameRepository_FindGameByIncludeUser_Call struct {
	*mock.Call
}

// FindGameByIncludeUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *MockIGameRepository_Expecter) FindGameByIncludeUser(ctx interface{}, userId interface{}) *MockIGameRepository_FindGameByIncludeUser_Call {
	return &MockIGameRepository_FindGameByIncludeUser_Call{Call: _e.mock.On("FindGameByIncludeUser", ctx, userId)}
}

func (_c *MockIGameRepository_FindGameByIncludeUser_Call) Run(run func(ctx context.Context, userId string)) *MockIGameRepository_FindGameByIncludeUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIGameRepository_FindGameByIncludeUser_Call) Return(games []models.Game, err error) *MockIGameRepository_FindGameByIncludeUser_Call {
	_c.Call.Return(games, err)
	return _c
}

func (_c *MockIGameRepository_FindGameByIncludeUser_Call) RunAndReturn(run func(ctx context.Context, userId string) ([]models.Game, error)) *MockIGameRepository_FindGameByIncludeUser_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIGameRepository
func (_mock *MockIGameRepository) Update(ctx context.Context, res iface.IModel) error {
	ret := _mock.Called(ctx, res)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, iface.IModel) error); ok {
		r0 = returnFunc(ctx, res)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIGameRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIGameRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - res iface.IModel
func (_e *MockIGameRepository_Expecter) Update(ctx interface{}, res interface{}) *MockIGameRepository_Update_Call {
	return &MockIGameRepository_Update_Call{Call: _e.mock.On("Update", ctx, res)}
}

func (_c *MockIGameRepository_Update_Call) Run(run func(ctx context.Context, res iface.IModel)) *MockIGameRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 iface.IModel
		if args[1] != nil {
			arg1 = args[1].(iface.IModel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIGameRepository_Update_Call) Return(err error) *MockIGameRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIGameRepository_Update_Call) RunAndReturn(run func(ctx context.Context, res iface.IModel) error) *MockIGameRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
