// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"snake-tournament/models/dto"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIGameService creates a new instance of MockIGameService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIGameService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIGameService {
	mock := &MockIGameService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIGameService is an autogenerated mock type for the IGameService type
type MockIGameService struct {
	mock.Mock
}

type MockIGameService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIGameService) EXPECT() *MockIGameService_Expecter {
	return &MockIGameService_Expecter{mock: &_m.Mock}
}

// CheckAvailableRenew provides a mock function for the type MockIGameService
func (_mock *MockIGameService) CheckAvailableRenew(ctx context.Context, id string, user dto.User) (bool, error) {
	ret := _mock.Called(ctx, id, user)

	if len(ret) == 0 {
		panic("no return value specified for CheckAvailableRenew")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dto.User) (bool, error)); ok {
		return returnFunc(ctx, id, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dto.User) bool); ok {
		r0 = returnFunc(ctx, id, user)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, dto.User) error); ok {
		r1 = returnFunc(ctx, id, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGameService_CheckAvailableRenew_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAvailableRenew'
type MockIGameService_CheckAvailableRenew_Call struct {
	*mock.Call
}

// CheckAvailableRenew is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - user dto.User
func (_e *MockIGameService_Expecter) CheckAvailableRenew(ctx interface{}, id interface{}, user interface{}) *MockIGameService_CheckAvailableRenew_Call {
	return &MockIGameService_CheckAvailableRenew_Call{Call: _e.mock.On("CheckAvailableRenew", ctx, id, user)}
}

func (_c *MockIGameService_CheckAvailableRenew_Call) Run(run func(ctx context.Context, id string, user dto.User)) *MockIGameService_CheckAvailableRenew_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 dto.User
		if args[2] != nil {
			arg2 = args[2].(dto.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIGameService_CheckAvailableRenew_Call) Return(b bool, err error) *MockIGameService_CheckAvailableRenew_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIGameService_CheckAvailableRenew_Call) RunAndReturn(run func(ctx context.Context, id string, user dto.User) (bool, error)) *MockIGameService_CheckAvailableRenew_Call {
	_c.Call.Return(run)
	return _c
}

// EnterToGame provides a mock function for the type MockIGameService
func (_mock *MockIGameService) EnterToGame(ctx context.Context, id string, user dto.User) (*dto.GameDto, error) {
	ret := _mock.Called(ctx, id, user)

	if len(ret) == 0 {
		panic("no return value specified for EnterToGame")
	}

	var r0 *dto.GameDto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dto.User) (*dto.GameDto, error)); ok {
		return returnFunc(ctx, id, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dto.User) *dto.GameDto); ok {
		r0 = returnFunc(ctx, id, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GameDto)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, dto.User) error); ok {
		r1 = returnFunc(ctx, id, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGameService_EnterToGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnterToGame'
type MockIGameService_EnterToGame_Call struct {
	*mock.Call
}

// EnterToGame is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - user dto.User
func (_e *MockIGameService_Expecter) EnterToGame(ctx interface{}, id interface{}, user interface{}) *MockIGameService_EnterToGame_Call {
	return &MockIGameService_EnterToGame_Call{Call: _e.mock.On("EnterToGame", ctx, id, user)}
}

func (_c *MockIGameService_EnterToGame_Call) Run(run func(ctx context.Context, id string, user dto.User)) *MockIGameService_EnterToGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 dto.User
		if args[2] != nil {
			arg2 = args[2].(dto.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIGameService_EnterToGame_Call) Return(gameDto *dto.GameDto, err error) *MockIGameService_EnterToGame_Call {
	_c.Call.Return(gameDto, err)
	return _c
}

func (_c *MockIGameService_EnterToGame_Call) RunAndReturn(run func(ctx context.Context, id string, user dto.User) (*dto.GameDto, error)) *MockIGameService_EnterToGame_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveGame provides a mock function for the type MockIGameService
func (_mock *MockIGameService) GetActiveGame(ctx context.Context, user dto.User) ([]dto.GameDto, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveGame")
	}

	var r0 []dto.GameDto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.User) ([]dto.GameDto, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.User) []dto.GameDto); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.GameDto)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGameService_GetActiveGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveGame'
type MockIGameService_GetActiveGame_Call struct {
	*mock.Call
}

// GetActiveGame is a helper method to define mock.On call
//   - ctx context.Context
//   - user dto.User
func (_e *MockIGameService_Expecter) GetActiveGame(ctx interface{}, user interface{}) *MockIGameService_GetActiveGame_Call {
	return &MockIGameService_GetActiveGame_Call{Call: _e.mock.On("GetActiveGame", ctx, user)}
}

func (_c *MockIGameService_GetActiveGame_Call) Run(run func(ctx context.Context, user dto.User)) *MockIGameService_GetActiveGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.User
		if args[1] != nil {
			arg1 = args[1].(dto.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIGameService_GetActiveGame_Call) Return(gameDtos []dto.GameDto, err error) *MockIGameService_GetActiveGame_Call {
	_c.Call.Return(gameDtos, err)
	return _c
}

func (_c *MockIGameService_GetActiveGame_Call) RunAndReturn(run func(ctx context.Context, user dto.User) ([]dto.GameDto, error)) *MockIGameService_GetActiveGame_Call {
	_c.Call.Return(run)
	return _c
}

// GetGamesForCurrentUser provides a mock function for the type MockIGameService
func (_mock *MockIGameService) GetGamesForCurrentUser(ctx context.Context, user dto.User) ([]dto.ResultGameDto, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GetGamesForCurrentUser")
	}

	var r0 []dto.ResultGameDto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.User) ([]dto.ResultGameDto, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.User) []dto.ResultGameDto); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ResultGameDto)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGameService_GetGamesForCurrentUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGamesForCurrentUser'
type MockIGameService_GetGamesForCurrentUser_Call struct {
	*mock.Call
}

// GetGamesForCurrentUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user dto.User
func (_e *MockIGameService_Expecter) GetGamesForCurrentUser(ctx interface{}, user interface{}) *MockIGameService_GetGamesForCurrentUser_Call {
	return &MockIGameService_GetGamesForCurrentUser_Call{Call: _e.mock.On("GetGamesForCurrentUser", ctx, user)}
}

func (_c *MockIGameService_GetGamesForCurrentUser_Call) Run(run func(ctx context.Context, user dto.User)) *MockIGameService_GetGamesForCurrentUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.User
		if args[1] != nil {
			arg1 = args[1].(dto.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIGameService_GetGamesForCurrentUser_Call) Return(resultGameDtos []dto.ResultGameDto, err error) *MockIGameService_GetGamesForCurrentUser_Call {
	_c.Call.Return(resultGameDtos, err)
	return _c
}

func (_c *MockIGameService_GetGamesForCurrentUser_Call) RunAndReturn(run func(ctx context.Context, user dto.User) ([]dto.ResultGameDto, error)) *MockIGameService_GetGamesForCurrentUser_Call {
	_c.Call.Return(run)
	return _c
}

// PasteResults provides a mock function for the type MockIGameService
func (_mock *MockIGameService) PasteResults(ctx context.Context, id string, dto1 dto.RecordCreateRequest, user dto.User) ([]dto.RecordDto, error) {
	ret := _mock.Called(ctx, id, dto1, user)

	if len(ret) == 0 {
		panic("no return value specified for PasteResults")
	}

	var r0 []dto.RecordDto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dto.RecordCreateRequest, dto.User) ([]dto.RecordDto, error)); ok {
		return returnFunc(ctx, id, dto1, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dto.RecordCreateRequest, dto.User) []dto.RecordDto); ok {
		r0 = returnFunc(ctx, id, dto1, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.RecordDto)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, dto.RecordCreateRequest, dto.User) error); ok {
		r1 = returnFunc(ctx, id, dto1, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGameService_PasteResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasteResults'
type MockIGameService_PasteResults_Call struct {
	*mock.Call
}

// PasteResults is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - dto1 dto.RecordCreateRequest
//   - user dto.User
func (_e *MockIGameService_Expecter) PasteResults(ctx interface{}, id interface{}, dto1 interface{}, user interface{}) *MockIGameService_PasteResults_Call {
	return &MockIGameService_PasteResults_Call{Call: _e.mock.On("PasteResults", ctx, id, dto1, user)}
}

func (_c *MockIGameService_PasteResults_Call) Run(run func(ctx context.Context, id string, dto1 dto.RecordCreateRequest, user dto.User)) *MockIGameService_PasteResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 dto.RecordCreateRequest
		if args[2] != nil {
			arg2 = args[2].(dto.RecordCreateRequest)
		}
		var arg3 dto.User
		if args[3] != nil {
			arg3 = args[3].(dto.User)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIGameService_PasteResults_Call) Return(recordDtos []dto.RecordDto, err error) *MockIGameService_PasteResults_Call {
	_c.Call.Return(recordDtos, err)
	return _c
}

func (_c *MockIGameService_PasteResults_Call) RunAndReturn(run func(ctx context.Context, id string, dto1 dto.RecordCreateRequest, user dto.User) ([]dto.RecordDto, error)) *MockIGameService_PasteResults_Call {
	_c.Call.Return(run)
	return _c
}

// SetPrize provides a mock function for the type MockIGameService
func (_mock *MockIGameService) SetPrize(ctx context.Context, id string, request dto.SelectPrizeDto, user dto.User) (*dto.ResultGameDto, error) {
	ret := _mock.Called(ctx, id, request, user)

	if len(ret) == 0 {
		panic("no return value specified for SetPrize")
	}

	var r0 *dto.ResultGameDto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dto.SelectPrizeDto, dto.User) (*dto.ResultGameDto, error)); ok {
		return returnFunc(ctx, id, request, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dto.SelectPrizeDto, dto.User) *dto.ResultGameDto); ok {
		r0 = returnFunc(ctx, id, request, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ResultGameDto)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, dto.SelectPrizeDto, dto.User) error); ok {
		r1 = returnFunc(ctx, id, request, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGameService_SetPrize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPrize'
type MockIGameService_SetPrize_Call struct {
	*mock.Call
}

// SetPrize is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - request dto.SelectPrizeDto
//   - user dto.User
func (_e *MockIGameService_Expecter) SetPrize(ctx interface{}, id interface{}, request interface{}, user interface{}) *MockIGameService_SetPrize_Call {
	return &MockIGameService_SetPrize_Call{Call: _e.mock.On("SetPrize", ctx, id, request, user)}
}

func (_c *MockIGameService_SetPrize_Call) Run(run func(ctx context.Context, id string, request dto.SelectPrizeDto, user dto.User)) *MockIGameService_SetPrize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 dto.SelectPrizeDto
		if args[2] != nil {
			arg2 = args[2].(dto.SelectPrizeDto)
		}
		var arg3 dto.User
		if args[3] != nil {
			arg3 = args[3].(dto.User)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIGameService_SetPrize_Call) Return(resultGameDto *dto.ResultGameDto, err error) *MockIGameService_SetPrize_Call {
	_c.Call.Return(resultGameDto, err)
	return _c
}

func (_c *MockIGameService_SetPrize_Call) RunAndReturn(run func(ctx context.Context, id string, request dto.SelectPrizeDto, user dto.User) (*dto.ResultGameDto, error)) *MockIGameService_SetPrize_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockIGameService
func (_mock *MockIGameService) Start(ctx context.Context, dto1 dto.GameCreateRequest, user dto.User) (*dto.GameDto, error) {
	ret := _mock.Called(ctx, dto1, user)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 *dto.GameDto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GameCreateRequest, dto.User) (*dto.GameDto, error)); ok {
		return returnFunc(ctx, dto1, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GameCreateRequest, dto.User) *dto.GameDto); ok {
		r0 = returnFunc(ctx, dto1, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GameDto)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.GameCreateRequest, dto.User) error); ok {
		r1 = returnFunc(ctx, dto1, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGameService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockIGameService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - dto1 dto.GameCreateRequest
//   - user dto.User
func (_e *MockIGameService_Expecter) Start(ctx interface{}, dto1 interface{}, user interface{}) *MockIGameService_Start_Call {
	return &MockIGameService_Start_Call{Call: _e.mock.On("Start", ctx, dto1, user)}
}

func (_c *MockIGameService_Start_Call) Run(run func(ctx context.Context, dto1 dto.GameCreateRequest, user dto.User)) *MockIGameService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.GameCreateRequest
		if args[1] != nil {
			arg1 = args[1].(dto.GameCreateRequest)
		}
		var arg2 dto.User
		if args[2] != nil {
			arg2 = args[2].(dto.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIGameService_Start_Call) Return(gameDto *dto.GameDto, err error) *MockIGameService_Start_Call {
	_c.Call.Return(gameDto, err)
	return _c
}

func (_c *MockIGameService_Start_Call) RunAndReturn(run func(ctx context.Context, dto1 dto.GameCreateRequest, user dto.User) (*dto.GameDto, error)) *MockIGameService_Start_Call {
	_c.Call.Return(run)
	return _c
}
