// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIModel creates a new instance of MockIModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIModel {
	mock := &MockIModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIModel is an autogenerated mock type for the IModel type
type MockIModel struct {
	mock.Mock
}

type MockIModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIModel) EXPECT() *MockIModel_Expecter {
	return &MockIModel_Expecter{mock: &_m.Mock}
}

// GetId provides a mock function for the type MockIModel
func (_mock *MockIModel) GetId() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetId")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIModel_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type MockIModel_GetId_Call struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
func (_e *MockIModel_Expecter) GetId() *MockIModel_GetId_Call {
	return &MockIModel_GetId_Call{Call: _e.mock.On("GetId")}
}

func (_c *MockIModel_GetId_Call) Run(run func()) *MockIModel_GetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIModel_GetId_Call) Return(s string) *MockIModel_GetId_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIModel_GetId_Call) RunAndReturn(run func() string) *MockIModel_GetId_Call {
	_c.Call.Return(run)
	return _c
}

// SetId provides a mock function for the type MockIModel
func (_mock *MockIModel) SetId(s string) {
	_mock.Called(s)
	return
}

// MockIModel_SetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetId'
type MockIModel_SetId_Call struct {
	*mock.Call
}

// SetId is a helper method to define mock.On call
//   - s string
func (_e *MockIModel_Expecter) SetId(s interface{}) *MockIModel_SetId_Call {
	return &MockIModel_SetId_Call{Call: _e.mock.On("SetId", s)}
}

func (_c *MockIModel_SetId_Call) Run(run func(s string)) *MockIModel_SetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIModel_SetId_Call) Return() *MockIModel_SetId_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIModel_SetId_Call) RunAndReturn(run func(s string)) *MockIModel_SetId_Call {
	_c.Run(run)
	return _c
}
