// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"snake-tournament/internal/iface"
	"snake-tournament/models"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/bson"
)

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Create(ctx context.Context, model iface.IModel) error {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, iface.IModel) error); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model iface.IModel
func (_e *MockIRepository_Expecter) Create(ctx interface{}, model interface{}) *MockIRepository_Create_Call {
	return &MockIRepository_Create_Call{Call: _e.mock.On("Create", ctx, model)}
}

func (_c *MockIRepository_Create_Call) Run(run func(ctx context.Context, model iface.IModel)) *MockIRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 iface.IModel
		if args[1] != nil {
			arg1 = args[1].(iface.IModel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_Create_Call) Return(err error) *MockIRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model iface.IModel) error) *MockIRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Delete(ctx context.Context, objectID bson.ObjectID) error {
	ret := _mock.Called(ctx, objectID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID) error); ok {
		r0 = returnFunc(ctx, objectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - objectID bson.ObjectID
func (_e *MockIRepository_Expecter) Delete(ctx interface{}, objectID interface{}) *MockIRepository_Delete_Call {
	return &MockIRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, objectID)}
}

func (_c *MockIRepository_Delete_Call) Run(run func(ctx context.Context, objectID bson.ObjectID)) *MockIRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_Delete_Call) Return(err error) *MockIRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, objectID bson.ObjectID) error) *MockIRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockIRepository
func (_mock *MockIRepository) FindById(ctx context.Context, id string, res *models.Game) error {
	ret := _mock.Called(ctx, id, res)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *models.Game) error); ok {
		r0 = returnFunc(ctx, id, res)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockIRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - res *models.Game
func (_e *MockIRepository_Expecter) FindById(ctx interface{}, id interface{}, res interface{}) *MockIRepository_FindById_Call {
	return &MockIRepository_FindById_Call{Call: _e.mock.On("FindById", ctx, id, res)}
}

func (_c *MockIRepository_FindById_Call) Run(run func(ctx context.Context, id string, res *models.Game)) *MockIRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *models.Game
		if args[2] != nil {
			arg2 = args[2].(*models.Game)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIRepository_FindById_Call) Return(err error) *MockIRepository_FindById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_FindById_Call) RunAndReturn(run func(ctx context.Context, id string, res *models.Game) error) *MockIRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Update(ctx context.Context, res iface.IModel) error {
	ret := _mock.Called(ctx, res)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, iface.IModel) error); ok {
		r0 = returnFunc(ctx, res)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - res iface.IModel
func (_e *MockIRepository_Expecter) Update(ctx interface{}, res interface{}) *MockIRepository_Update_Call {
	return &MockIRepository_Update_Call{Call: _e.mock.On("Update", ctx, res)}
}

func (_c *MockIRepository_Update_Call) Run(run func(ctx context.Context, res iface.IModel)) *MockIRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 iface.IModel
		if args[1] != nil {
			arg1 = args[1].(iface.IModel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_Update_Call) Return(err error) *MockIRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_Update_Call) RunAndReturn(run func(ctx context.Context, res iface.IModel) error) *MockIRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
