// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/alexsuslov/ehttp/pkg/hticket"
	mock "github.com/stretchr/testify/mock"
)

// NewMockITickets creates a new instance of MockITickets. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITickets(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITickets {
	mock := &MockITickets{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockITickets is an autogenerated mock type for the ITickets type
type MockITickets struct {
	mock.Mock
}

type MockITickets_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITickets) EXPECT() *MockITickets_Expecter {
	return &MockITickets_Expecter{mock: &_m.Mock}
}

// CloseTicket provides a mock function for the type MockITickets
func (_mock *MockITickets) CloseTicket(ctx context.Context, game hticket.IGame, user hticket.IUser) error {
	ret := _mock.Called(ctx, game, user)

	if len(ret) == 0 {
		panic("no return value specified for CloseTicket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, hticket.IGame, hticket.IUser) error); ok {
		r0 = returnFunc(ctx, game, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockITickets_CloseTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseTicket'
type MockITickets_CloseTicket_Call struct {
	*mock.Call
}

// CloseTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - game hticket.IGame
//   - user hticket.IUser
func (_e *MockITickets_Expecter) CloseTicket(ctx interface{}, game interface{}, user interface{}) *MockITickets_CloseTicket_Call {
	return &MockITickets_CloseTicket_Call{Call: _e.mock.On("CloseTicket", ctx, game, user)}
}

func (_c *MockITickets_CloseTicket_Call) Run(run func(ctx context.Context, game hticket.IGame, user hticket.IUser)) *MockITickets_CloseTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 hticket.IGame
		if args[1] != nil {
			arg1 = args[1].(hticket.IGame)
		}
		var arg2 hticket.IUser
		if args[2] != nil {
			arg2 = args[2].(hticket.IUser)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockITickets_CloseTicket_Call) Return(err error) *MockITickets_CloseTicket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockITickets_CloseTicket_Call) RunAndReturn(run func(ctx context.Context, game hticket.IGame, user hticket.IUser) error) *MockITickets_CloseTicket_Call {
	_c.Call.Return(run)
	return _c
}
